CREATE TABLE ztb_file_processing_task (
    task_id VARCHAR(64) PRIMARY KEY,
    project_id VARCHAR(64) NOT NULL,
    file_id VARCHAR(128) NOT NULL,
    file_name VARCHAR(512) NOT NULL,
    file_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    error_message CLOB,
    llm_raw_json CLOB,
    result_summary_json CLOB,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP,
    finished_at TIMESTAMP
);

CREATE INDEX idx_ztb_task_business
    ON ztb_file_processing_task (project_id, file_id, file_type, created_at);

CREATE TABLE ztb_project_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id VARCHAR(64) NOT NULL,
    file_id VARCHAR(128) NOT NULL,
    file_name VARCHAR(512) NOT NULL,
    tender_company_name VARCHAR(512),
    agency_name VARCHAR(512),
    project_name VARCHAR(512),
    bid_submit_start_time TIMESTAMP,
    bid_submit_end_time TIMESTAMP,
    range_start_time TIMESTAMP,
    range_end_time TIMESTAMP,
    all_time_points_json CLOB,
    task_id VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_ztb_project_info_file UNIQUE (project_id, file_id)
);

CREATE TABLE ztb_project_bidder_company (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id VARCHAR(64) NOT NULL,
    file_id VARCHAR(128) NOT NULL,
    file_name VARCHAR(512) NOT NULL,
    bid_company_name VARCHAR(512),
    bidder_contact_phone VARCHAR(128),
    registered_address VARCHAR(1024),
    mailing_address VARCHAR(1024),
    project_management_personnel_json CLOB,
    task_id VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_ztb_bidder_file UNIQUE (project_id, file_id)
);
